# Generated by Django 3.2 on 2023-10-11 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('total_cleared', models.FloatField(blank=True, default=0.0, null=True)),
                ('outstanding', models.FloatField(blank=True, default=0.0, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('date_of_birth', models.CharField(blank=True, max_length=10)),
                ('profile_picture', models.ImageField(blank=True, upload_to='userprofile/%Y%m%d/')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_support', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paystack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=1000000)),
                ('amount', models.CharField(max_length=1000000)),
                ('email', models.EmailField(blank=True, max_length=3000, null=True)),
                ('reference', models.CharField(max_length=200)),
                ('generated', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-generated',),
            },
        ),
        migrations.CreateModel(
            name='Userhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=40, null=True)),
                ('amount', models.CharField(blank=True, max_length=30, null=True)),
                ('transaction', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('date_created', models.DateField()),
                ('paystack', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.paystack')),
            ],
            options={
                'verbose_name_plural': 'User Histories',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='SchoolFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, unique=True)),
                ('year1_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year2_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year3_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year4_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year5_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
