# Generated by Django 3.2 on 2023-10-11 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolfees',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='course_name',
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
