# Generated by Django 3.2 on 2023-10-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231011_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='matric_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
