# Generated by Django 3.2 on 2023-10-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_session'),
        ('accounts', '0004_account_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faculty'),
        ),
        migrations.AlterField(
            model_name='account',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.session'),
        ),
    ]
