# Generated by Django 3.2 on 2023-10-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231011_1617'),
        ('accounts', '0005_auto_20231011_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolfees',
            options={'ordering': ('-date',), 'verbose_name': 'School Fee', 'verbose_name_plural': 'School Fees'},
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='year1_fee',
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='year2_fee',
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='year3_fee',
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='year4_fee',
        ),
        migrations.RemoveField(
            model_name='schoolfees',
            name='year5_fee',
        ),
        migrations.AddField(
            model_name='account',
            name='year1_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year2_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year3_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year4_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='year5_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schoolfees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
