# Generated by Django 3.2 on 2023-10-11 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20231011_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhistory',
            options={'ordering': ('-date_created',), 'verbose_name': 'User Payment History', 'verbose_name_plural': 'User Payment Histories'},
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='paystack',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='ref',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
