# Generated by Django 3.2 on 2023-10-20 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231011_1617'),
        ('accounts', '0010_auto_20231019_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentfees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', unique=True),
        ),
        migrations.AlterField(
            model_name='facultyfees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', unique=True),
        ),
        migrations.AlterField(
            model_name='libraryfees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', unique=True),
        ),
        migrations.AlterField(
            model_name='medicalfees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', unique=True),
        ),
        migrations.AlterField(
            model_name='schoolfees',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', unique=True),
        ),
    ]
